// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_ZufjrkuDatHAHUrx-Y50jo3IBhje68',
    appId: '1:134228452829:web:e45083e73a92543d050234',
    messagingSenderId: '134228452829',
    projectId: 'skin-disease-app-51ccb',
    authDomain: 'skin-disease-app-51ccb.firebaseapp.com',
    storageBucket: 'skin-disease-app-51ccb.firebasestorage.app',
    measurementId: 'G-DCRW3BEHBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqA4ScUPOao5zciSBTzGZCo-OShHMmmxI',
    appId: '1:134228452829:android:d1924d969e8fcf0f050234',
    messagingSenderId: '134228452829',
    projectId: 'skin-disease-app-51ccb',
    storageBucket: 'skin-disease-app-51ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawAP56q2CqLS06APQx9xaU2dnGaboIE8',
    appId: '1:134228452829:ios:d80731383e966e2e050234',
    messagingSenderId: '134228452829',
    projectId: 'skin-disease-app-51ccb',
    storageBucket: 'skin-disease-app-51ccb.firebasestorage.app',
    iosBundleId: 'vn.edu.ntu.truongvu.skinDiseaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDawAP56q2CqLS06APQx9xaU2dnGaboIE8',
    appId: '1:134228452829:ios:d80731383e966e2e050234',
    messagingSenderId: '134228452829',
    projectId: 'skin-disease-app-51ccb',
    storageBucket: 'skin-disease-app-51ccb.firebasestorage.app',
    iosBundleId: 'vn.edu.ntu.truongvu.skinDiseaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg_ZufjrkuDatHAHUrx-Y50jo3IBhje68',
    appId: '1:134228452829:web:6ca7d1512a0d6d0b050234',
    messagingSenderId: '134228452829',
    projectId: 'skin-disease-app-51ccb',
    authDomain: 'skin-disease-app-51ccb.firebaseapp.com',
    storageBucket: 'skin-disease-app-51ccb.firebasestorage.app',
    measurementId: 'G-S34DJBSJ0H',
  );
}
